### Register
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "password":"123456",
    "phone":"0123456787",
    "name":"Tuan",
    "role":"USER",
}

### Register

POST http://localhost:5000/api/auth/signin
Content-Type: application/json

{
    "password":"123456",
    "phone":"0123456789"
}
